on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  DeterminateCI:
    uses: aloshy-ai/ci/.github/workflows/workflow.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      visibility: public
      enable-ssh-agent: true
      enable-cachix: true
    secrets:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
